name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  Unit_tests:
    name: Run unit tests on PR in master
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Init tests
        run: ./gradlew test
    